name: merge-main-into-small-image.yml
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: authenticate to ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e7y7s7r3

      - name: docker build image
        run: |
          docker build -t nextapp .

      - name: docker tag image
        run: |
          docker tag nextapp:latest public.ecr.aws/e7y7s7r3/nextapp:latest

      - name: docker push image
        run: |
          docker push public.ecr.aws/e7y7s7r3/nextapp:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster node-app --service node-service --force-new-deployment
